#!/bin/bash
#SBATCH -J gausssian_pyfrag
#SBATCH -t 5:00
#SBATCH -N 1
#SBATCH --tasks-per-node=16
#SBATCH --partition=short
#SBATCH -o job-%j.stdout
#SBATCH -e job-%j.stderr

module load g09/A02

export NSCM=16

export WORK_TMPDIR=$TMPDIR
cd $WORK_TMPDIR

