#!/bin/bash
#SBATCH -J orca_pyfrag
#SBATCH -t 5:00
#SBATCH -N 1
#SBATCH --tasks-per-node=16
#SBATCH --partition=tc
#SBATCH -o job-%j.stdout
#SBATCH -e job-%j.stderr

module load shared
module load orca/6.0.0

export NSCM=16

export WORK_TMPDIR=$TMPDIR
cd $WORK_TMPDIR


