#!/bin/bash
#SBATCH -N 1
#SBATCH -t 12:00:00
#SBATCH --ntasks-per-node=32
#SBATCH --partition=tc
#SBATCH --output=methane.out
#SBATCH --error=methane.err
module load 2025
module load shared
module load ams/2021.102-zen 
module list
source ${HOSTPYFRAG}/src/pyfrag/venv_runner.sh && run_pyfrag_cluster ${HOSTPYFRAG}/src/pyfrag/cluster_runner.py --backend adf_new --job-dir $(pwd) --input-file new_ams_methane.in \
--name methane \
--coordfile methane.xyz \
--frag1_indices  1-4 \
--frag2_indices  5 \
--frag1_energy   0 \
--frag2_energy   0 \
--bondlength 1 5 \
--log_level debug \
--overlap A1 frag1 3_A A frag2 1_A \
--overlap A1 frag1 3_B A frag2 1_B \
--overlap A1 frag1 2_B A frag2 1_B \
--orbitalenergy A1 frag1 3_A \
--orbitalenergy A1 frag2 1_A \
--population frag1 HOMO \
--population frag2 HOMO \
--population A1 frag1 3_A \
--population A frag2 1_A \
--fragment1_EXTRA /net/sys/pscst001/export/tc/sle337/bin/PyFrag/example/PyFrag2025/Methane/fragment1_EXTRA \
--fragment2_EXTRA /net/sys/pscst001/export/tc/sle337/bin/PyFrag/example/PyFrag2025/Methane/fragment2_EXTRA \
--complex_EXTRA /net/sys/pscst001/export/tc/sle337/bin/PyFrag/example/PyFrag2025/Methane/complex_EXTRA \
--adfinputfile /net/sys/pscst001/export/tc/sle337/bin/PyFrag/example/PyFrag2025/Methane/adfinputfile \
